#!/bin/sh /etc/rc.common

START=55
STOP=45
USE_PROCD=1

port=54122
remote_host="bruna.kir.elagin.me"
remote_user="router"
identity_file="/root/router.key"

start_service() {
  [ $(ubus call network.interface.wan status | jsonfilter -e "@.up") = "true" ]
  wan_up=$?

  procd_open_instance
  if [ $wan_up -eq 0 ]; then
    procd_set_param command ssh -i "$identity_file" -T -N -y -K 60 -R ":$port:localhost:22" -o "ExitOnForwardFailure=yes" "$remote_user@$remote_host"
    logger -p daemon.info -t 'sshtun' 'wan is up, starting'
  else
    procd_set_param command tail -f /dev/null
    logger -p daemon.info -t 'sshtun' 'wan is down, waiting'
  fi
  procd_set_param respawn 3600 5 -1
  procd_close_instance
}

service_triggers() {
  procd_add_reload_interface_trigger wan
}
