#!/bin/sh


uci -q delete network.wan.dns
uci batch <<EOF
set network.wan.peerdns='0'
EOF
uci -q delete network.wan6.dns
uci batch <<EOF
set network.wan6.peerdns='0'
EOF
uci commit network

uci batch <<EOF
set dhcp.odhcpd.maindhcp='1'
EOF
uci commit dhcp

exit 0
