#!/bin/sh

led=$(uci get system.wps.sysfs)
[ -n "$led" ] || return 0
path="/sys/class/leds/$led"

case "$ACTION" in
  pressed)
    echo 255 > "$path/brightness"
    ;;
  released)
    echo 0 > "$path/brightness"
    ;;
esac

return 0
