#!/bin/sh

. /lib/functions.sh


uci batch <<EOF
set wireless.@wifi-iface[0].ssid='kirNet'
set wireless.@wifi-iface[0].encryption='psk2'
set wireless.@wifi-iface[0].key='probably_positive_inside_detail'

set wireless.radio0.country='RU'
set wireless.radio0.channel='48'
set wireless.radio0.hwmode='11a'
set wireless.radio0.htmode='HT40'

delete wireless.radio0.disabled
EOF

uci commit wireless

exit 0
