#!/bin/sh

# Note: this test does not work for removing the device (as the file is gone)
if [ "$(readlink -f "/sys/$DEVPATH/device/subsystem")" == "/sys/bus/usb" ] ; then
  case $ACTION in
    add)
      uci set network.wan.ifname="$INTERFACE"
      uci commit network
      /etc/init.d/network reload

      uci set system.led_usb.dev="$INTERFACE"
      uci commit system
      /etc/init.d/led reload
      ;;
  esac
fi
