#!/bin/sh

if [ "${DEVPATH#/devices/platform/ehci-platform/usb1/}" != "$DEVPATH" ] ; then
  case $ACTION in
    add)
      uci set network.wan.ifname="$INTERFACE"
      uci commit network
      /etc/init.d/network reload

      uci set system.led_usb.dev="$INTERFACE"
      uci commit system
      /etc/init.d/led reload
      ;;
  esac
fi
