#!/bin/sh


uci batch <<EOF
add_list network.@device[0].ports='eth1'

set network.lan.proto='dhcp'
EOF
uci commit network

uci batch <<EOF
set dhcp.lan.ignore='1'
set dhcp.lan.dhcpv4='disabled'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra_management='0'
set dhcp.lan.ra='disabled'
set dhcp.lan.ndp='disabled'
EOF
uci commit dhcp

exit 0
