#!/bin/sh

for i in 0 1; do
uci batch <<EOF
set wireless.@wifi-iface[$i].ssid='kirNet'
set wireless.@wifi-iface[$i].encryption='psk2'
set wireless.@wifi-iface[$i].key='<redacted>'

delete wireless.radio$i.disabled
EOF
done

for i in 0 1; do
uci batch <<EOF
set wireless.@wifi-device[$i].country='US'
set wireless.@wifi-device[$i].txpower='16'
EOF
done

uci batch <<EOF
set wireless.radio0.disabled='1'
set wireless.radio1.channel='100'

set wireless.default_radio1.ieee80211r='1'
set wireless.default_radio1.nasid='488f5a7db36f'
EOF

uci commit wireless


exit 0
