#!/bin/sh


uci batch <<EOF
set system.@system[0].hostname='dacha'
set system.@system[0].timezone='MSK-3'
set system.@system[0].log_size='1024'
EOF

## LED: LAN
#uci batch <<EOF
#set system.led_lan='led'
#set system.led_lan.name='LAN'
#set system.led_lan.sysfs='tl-mr3020-v3:green:lan'
#set system.led_lan.trigger='netdev'
#set system.led_lan.dev='eth0'
#set system.led_lan.mode='link tx rx'
#EOF

# LED: uplink
uci batch <<EOF
set system.led_usb='led'
set system.led_usb.name='USB'
set system.led_usb.sysfs='tl-mr3020-v3:green:3g'
set system.led_usb.trigger='netdev'
set system.led_usb.dev='eth1'
set system.led_usb.mode='link tx rx'
EOF

# LED: WPS
uci batch <<EOF
set system.led_wps='led'
set system.led_wps.name='WPS'
set system.led_wps.sysfs='tl-mr3020-v3:green:wps'
set system.led_wps.trigger='none'
set system.led_wps.default='0'
EOF

uci commit system

exit 0
