#!/bin/sh


uci batch <<EOF
set network.lan.ipaddr='192.168.5.1'
set network.lan.netmask='255.255.255.0'
EOF
uci commit network

uci batch <<EOF
set dhcp.local.start='5'
set dhcp.local.limit='245'
set dhcp.local.dhcpv4='server'
set dhcp.local.dhcpv6='disabled'
EOF
uci commit dhcp

exit 0
