#!/bin/sh


uci batch <<EOF
set network.lan.ipaddr='192.168.5.1'
set network.lan.netmask='255.255.255.0'
EOF
uci commit network

uci batch <<EOF
set dhcp.lan.start='5'
set dhcp.lan.limit='245'
set dhcp.lan.dhcpv4='server'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra_management='0'
set dhcp.lan.ra='server'
set dhcp.lan.ndp='disabled'
EOF
uci commit dhcp

exit 0
