#!/bin/sh

. /lib/functions.sh


local hostname=`uci_get system '@system[0]' hostname`

if [ -z "$hostname" ]; then
    exit 0
fi

handle_interface() {
    local iface="$1"
    local proto
    config_get proto "$iface" proto
    if [ "$proto" = "dhcp" -o "$proto" = "dhcpv6" ]; then
        uci_set network "$iface" hostname "$hostname"
    fi
}
config_load network
config_foreach handle_interface interface

uci_commit network

exit 0
