#!/bin/sh


# FIXME: this will add a new device even if it exists
uci batch <<EOF
add network device
set network.@device[-1].name='br-wan'
set network.@device[-1].type='bridge'
add_list network.@device[-1].ports='eth1'

set network.wan.device='br-wan'
set network.wan.proto='dhcp'
set network.wan6.device='br-wan'
set network.wan6.proto='dhcpv6'
EOF
uci commit network

uci batch <<EOF
set dhcp.lan.start='10'
set dhcp.lan.limit='240'
set dhcp.lan.dhcpv4='server'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra_management='0'
set dhcp.lan.ra='server'
set dhcp.lan.ndp='disabled'
EOF
uci commit dhcp

exit 0
