#!/bin/sh


uci batch <<EOF
set network.wan.type='bridge'
set network.wan.proto='dhcp'
EOF
uci commit network

uci batch <<EOF
set dhcp.lan.start='10'
set dhcp.lan.limit='240'
set dhcp.lan.dhcpv4='server'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra_management='0'
set dhcp.lan.ra='server'
set dhcp.lan.ndp='disabled'
EOF
uci commit dhcp

exit 0
