#!/bin/sh


uci batch <<EOF
set network.lan.ipaddr='172.22.0.1'
set network.lan.netmask='255.255.255.0'
EOF
uci commit network

uci batch <<EOF
set dhcp.lan.start='10'
set dhcp.lan.limit='240'
EOF
uci commit dhcp

exit 0
