#!/bin/sh

uci batch <<EOF
set network.wan.proto='pppoe'
set network.wan.username='ptn'
set network.wan.password='ptn'
set network.wan.mtu='1492'
EOF
uci -q delete network.wan.dns
uci batch <<EOF
add_list network.wan.dns='1.1.1.1'
add_list network.wan.dns='1.0.0.1'
add_list network.wan.dns='2606:4700:4700::1111'
add_list network.wan.dns='2606:4700:4700::1001'
EOF
uci commit network

exit 0
